#!/bin/sh

if [ x$ACT_HOME = x ]
then
	echo "Please set the environment variable ACT_HOME to the install directory"
        exit 1
fi

./check_omp.sh || exit 1

cxx_compiler=`cat CXX_COMPILER`

cmake_build() {
  dir=$1
  echo 
  echo "#### Building and installing package: $1 ####"
  echo
  (cd $dir; if [ -x ./configure ]; then ./configure; fi; if [ ! -d build ]; then mkdir build; fi; cd build; cmake -DCMAKE_INSTALL_PREFIX=$ACT_HOME -DCMAKE_CXX_COMPILER=$cxx_compiler .. && make && make install) || exit 1
}

cmake_build_bipart() {
  dir=BiPart
  echo
  echo "#### Building and installing package: Bipart ####"
  echo
  (cd BiPart; if [ ! -d build ]; then mkdir build; fi; cd build; LEF_ROOT=$ACT_HOME GALOIS_INCLUDE=$ACT_HOME/include GALOIS_LIB=$ACT_HOME/lib DEF_ROOT=$ACT_HOME cmake -DCMAKE_INSTALL_PREFIX=$ACT_HOME -DCMAKE_CXX_COMPILER=$cxx_compiler ..  && make && make install) || exit 1
}

act_tool_build() {
  dir=$1
  echo 
  echo "#### Building and installing package: $1 ####"
  echo
  (cd $dir; if [ -x ./configure ]; then ./configure; fi; make CXX=$cxx_compiler depend && make CXX=$cxx_compiler && make install) || exit 1
}

#
# Apply patches
#
echo "Applying patch to Galois library..."
if [ ! -f patched ]
then
   (cd Galois; 
     patch -p0 < ../extra/Galois;
     patch -p0 < ../extra/Galois2;
     patch -p0 < ../extra/Galois3;
     patch -p0 < ../extra/Galois4
   )
   touch patched
fi

#
# Build and install the ACT library
#
echo
echo "####  Building and installing the core ACT library ####"
echo
export VLSI_TOOLS_SRC=`pwd`/act
(cd act; ./configure $ACT_HOME; ./build $cxx_compiler; make install) || exit 1

#
# Build and install the Galois library
#
cmake_build Galois
if [ -f $ACT_HOME/lib64/libgalois_shmem.a -a ! -f $ACT_HOME/lib/libgalois_shmem.a ]
then
   ln -s $ACT_HOME/lib64/libgalois_shmem.a $ACT_HOME/lib/libgalois_shmem.a
fi

#
# Build and install the LEF/DEF library
#
echo
echo "####  Building and installing the LEF/DEF parser ####"
echo
(cd lefdef; make && make install) || exit 1

#
# Build and install... 

# phyDB
cmake_build phyDB

# layout
act_tool_build layout

# BiPart
cmake_build_bipart

# Dali
cmake_build Dali

# PWRoute
cmake_build PWRoute

# SPRoute
cmake_build SPRoute

# TritonRoute-WXL
cmake_build TritonRoute-WXL

# interact
act_tool_build interact

# stdlib
act_tool_build stdlib

# expropt
act_tool_build expropt

#
# chp2prs
act_tool_build chp2prs

#
# dflowmap
cmake_build dflowmap

#
# prs2fpga
act_tool_build prs2fpga

#
# xcell
act_tool_build xcell

#
# dflow2dot
act_tool_build dflow2dot

#
# sky130l
act_tool_build sky130l

# actsim
echo 
echo "#### Building actsim ####"
echo 
(cd actsim; ./configure; ./build.sh; make install) || exit 1
