#!/bin/sh


echo "Cleaning all directories..."

echo "*** act ***"
(cd act; make realclean)

echo "*** lefdef ***"
(cd lefdef; make clean)

for i in Galois phyDB BiPart Dali PWRoute SPRoute TritonRoute-WXL dflowmap
do
	echo "*** $i ***"
	(cd $i; rm -rf build)
done

for i in interact layout expropt chp2prs prs2fpga xcell dflow2dot actsim
do
   echo "*** $i ***"
   (cd $i; make realclean)
done

if [ -f timing/actpin.h ]
then
   echo "*** timing ***"
   (cd timing/cyclone; rm -rf build)
   (cd timing/galois_eda; rm -rf build)
fi
