#!/bin/sh


echo "Cleaning all directories..."

echo "*** act ***"
(cd act; make realclean)

echo "*** lefdef ***"
(cd lefdef; make clean)

for i in Galois phyDB BiPart Dali PWRoute SPRoute TritonRoute-WXL dflowmap
do
	echo "*** $i ***"
	(cd $i; rm -rf build)
done

echo "*** interact ***"
(cd interact; make realclean)

echo "*** layout ***"
(cd layout; make realclean)

echo "*** expropt ***"
(cd expropt; make realclean)

echo "*** chp2prs ***"
(cd chp2prs; make realclean)

echo "*** dflowmap ***"
(cd dflowmap; rm -rf build)

echo "*** prs2fpga ***"
(cd prs2fpga; make realclean)

echo "*** actsim ***"
(cd actsim; make realclean)
