#!/bin/sh

#
# Copyright 2022 Ole Richter - University of Groningen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ x$ACT_HOME = x ]
then
	echo "Please set the environment variable ACT_HOME to the install directory"
        exit 1
fi

if [ x$EDA_SRC = x ]
then
	export EDA_SRC=$(pwd)
fi
# make sure $ACT_HOME/bin is highest prio for the tests
export PATH=$ACT_HOME/bin:${PATH}
export VLSI_TOOLS_SRC=${EDA_SRC}/act

# tell the test scripts that you want to test the installed versions of the tools
export ACT_TEST_INSTALL="true"

# the act make file configuration is needed at the source to run make test, 
# if running the tests from unconfigured sources
if [ ! -f $VLSI_TOOLS_SRC/scripts/config ]; then
    cp $ACT_HOME/scripts/config $VLSI_TOOLS_SRC/scripts/
fi

# print environment for debugging
echo "###################"
echo "environment"
echo "ACT_HOME: $ACT_HOME"
echo "VLSI_TOOLS_SRC: $VLSI_TOOLS_SRC"
echo "EDA_SRC: $EDA_SRC"
echo "PATH: $PATH"
echo "###################"
echo 
echo "#### all test suits ####"
echo

#run all availible test in order
for test in tests/0*test.sh; do
    bash $test || exit 1
done