version: 2

jobs:
   ubuntu:
      docker:
         - image: default
      steps:
         - checkout
         - run: |
              echo "Hello"
              apt-get -q update -y
              DEBIAN_FRONTEND=noninteractive apt-get -q install -y libedit-dev zlib1g-dev m4 build-essential cmake libfmt-dev git cmake libboost-all-dev libopenmpi-dev llvm flex bison
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build && ./run.sh

   alpine:
      docker:
         - image: alpine:latest
      steps:
         - checkout
         - run: |
              apk update
              apk add libedit-dev zlib-dev m4 make cmake fmt-dev git boost-dev openmpi-dev llvm flex bison gcc g++ patch numactl-dev
              git clone https://github.com/asyncvlsi/actflow
              cd actflow
              git submodule update --init --recursive
              mkdir /usr/local/cad
              export ACT_HOME=/usr/local/cad
              ./build && ./run.sh

workflows:
   version: 2
   build:
      jobs:
         - ubuntu
         - alpine
